[project]
name = "blackjack-v3"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "deap>=1.4.3",
    "gymnasium>=1.2.0",
    "numpy<2.0",
    "pandas>=2.3.2",
    "sb3-contrib>=2.7.0",
    "scikit-learn>=1.7.1",
    "stable-baselines3[extra]>=2.7.0",
    "tianshou>=0.5.1",
    "torch>=2.8.0",
    "xgboost>=3.0.5",
]
